version: 2
jobs: 
  terraform-prod-plan:
    docker:
    - image: eu.gcr.io/pi-ostelco-prod/terraform-gcloud:11.13
      environment: 
        CLUSTER: prod
        GOOGLE_CREDENTIALS: /tmp/credentials.json

    working_directory: ~/repo

    steps:
    - checkout
    - run:
        name: running terraform plan for prod cluster
        command: |
          /docker-entrypoint.sh
          terraform init
          terraform plan \
          -var cluster_admin_password=$PROD_CLUSTER_PASSWORD


  terraform-prod-apply:
    docker:
    - image: eu.gcr.io/pi-ostelco-prod/terraform-gcloud:11.13
      environment: 
        CLUSTER: prod
        GOOGLE_CREDENTIALS: /tmp/credentials.json

    working_directory: ~/repo

    steps:
    - checkout
    - run:
        name: running terraform apply for prod cluster
        command: |
          /docker-entrypoint.sh
          terraform init
          terraform apply --auto-approve  \
          -var cluster_admin_password=$PROD_CLUSTER_PASSWORD 
          .circleci/store_cluster_certs.sh 

    - persist_to_workspace:
          root: ~/repo/
          paths:
            - static_ip.txt
            - endpoint.txt 
            - keys/*     

  deploy-prod-utilities: 
    docker:
    - image: praqma/helmsman:v1.8.1-helm-v2.11.0

    working_directory: ~/repo

    steps:
    - checkout
    - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/repo  
    - run:
        name: deploying utilities/dependencies to prod cluster with Helmsman
        command: | 
          echo $PI_PROD_GOOGLE_CREDENTIALS > /tmp/credentials.json
          export GOOGLE_APPLICATION_CREDENTIALS=/tmp/credentials.json
          export PI_PROD_K8S_ENDPOINT=https://$(cat endpoint.txt)
          export AMBASSADOR_STATIC_IP=$(cat static_ip.txt)      
          helmsman --apply --keep-untracked-releases --suppress-diff-secrets -f .circleci/helmsman-prod-utilities.toml            

workflows:
  version: 2
  clusters-plan-approve-and-deploy:
    jobs:
    - terraform-prod-plan:
        filters:
          branches:
            only:
            - master

    - hold-before-updating-prod-cluster:
        type: approval
        requires:
        - terraform-prod-plan

    - terraform-prod-apply:
        requires:
        - hold-before-updating-prod-cluster 
        
    - deploy-prod-utilities:
        requires:
          - terraform-prod-apply       